services:
  postgres:
    image: postgres:16
    container_name: libra-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: libra_db
      POSTGRES_USER: libra_user
      POSTGRES_PASSWORD: libra_pass
    volumes:
      - libra_pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U libra_user -d libra_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [libra-net]

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/libra_db?currentSchema=auth
      SPRING_DATASOURCE_USERNAME: libra_user
      SPRING_DATASOURCE_PASSWORD: libra_pass
    ports: ["8081:8080"]
    depends_on:
      postgres:
        condition: service_healthy
    networks: [libra-net]

  profile-service:
    build:
      context: .
      dockerfile: services/profile-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/libra_db?currentSchema=profile
      SPRING_DATASOURCE_USERNAME: libra_user
      SPRING_DATASOURCE_PASSWORD: libra_pass
    ports: [ "8082:8080" ]
    depends_on:
      postgres:
        condition: service_healthy
    networks: [libra-net]

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports: ["8080:8080"]
    depends_on:
      - auth-service
      - profile-service
    networks: [libra-net]

volumes:
  libra_pgdata:

networks:
  libra-net: