spring:
  application:
    name: event-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5454/meetflow_db?currentSchema=event}
    username: ${SPRING_DATASOURCE_USERNAME:mfuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mfpass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
